Final response improvements
h2oai/h2ogpt pull request #1863
Opened 2024-10-01 10:44 UTC by fatihozturkh2o

- Improving final agent response via passing instructions in code execution notes.
   - After executed_code_note, now also passing final_answer_guidelines like this:
```
        ret = self.truncate_output(ret)
        ret = self.executed_code_note(ret)
        ret = self.final_answer_guidelines(ret)
```
With the new instructions, aiming: 
- to make final message sound directly talking to the main user
- to have the actual answer the user was looking for (e.g. the code itself rather than the ouput etc.)
- to avoid internal agent expressions like 'Thank you for providing code execution output' etc.
- to still keep the LLM's own expressiveness after providing the actual answer (You can see it in the recording below, claude now starts with the actual answer but continues with its own explanations)

#### How it looks on main (without final_answer_guidelines)

https://github.com/user-attachments/assets/9402dda7-df4e-44da-b446-3172754b5905

#### How it looks on this PR (with final_answer_guidelines)

https://github.com/user-attachments/assets/86012a57-c5c6-4a45-97ad-b86170dd7e2b

2024-10-01 13:31 UTC, fatihozturkh2o commented
RAG question on main branch:
<img width="1277" alt="Screenshot 2024-10-01 at 4 30 31 PM" src="https://github.com/user-attachments/assets/6dc60cdb-21b7-428a-8240-638aa8b92a99">

same RAG question on this PR branch:
<img width="1326" alt="Screenshot 2024-10-01 at 4 30 42 PM" src="https://github.com/user-attachments/assets/d9def2da-600e-4431-93a6-2018b7c95cb4">

2024-10-01 18:24 UTC, pseudotensor commented on openai_server/autogen_utils.py
> +* Terminate the chat by having <FINISHED_ALL_TASKS> string in your final answer.
This whole text sounds like it applies to the very end, but this text block would appear after every code execution event.  I'd expect all this phrasing will lead to early termination of the iterations.

2024-10-01 19:12 UTC, pseudotensor commented on openai_server/autogen_utils.py
> +* Terminate the chat by having <FINISHED_ALL_TASKS> string in your final answer.
These kinds of phrasings are more appropriate for the no code block, because that is when there is a high likelihood of it being the final answer, and then it's job is to just repeat that final answer.

2024-10-01 21:41 UTC, fatihozturkh2o commented on openai_server/autogen_utils.py
> +* Identify the first user request in the chat history and start your response by providing a direct answer to that request by only using the information avaiable in the chat history.
Even though I haven't noticed it in my test chats, it sounds reasonable what you said. So changed. Wdyt now? https://github.com/h2oai/h2ogpt/pull/1863/commits/aadf97b3de785970a68cbf2978f4fdfd1c7de1cb

2024-10-02 07:32 UTC, pseudotensor approved these changes

2024-10-02 07:51 UTC, pseudotensor requested changes
see comments

2024-10-02 09:12 UTC, pseudotensor commented
Yes let's see if we can isolate the "final" block and (without repeating code) use in both system prompt and that final block.

2024-10-05 06:55 UTC, pseudotensor commented
@fatihozturkh2o 

Did you plan to still work on this?  I think the resulting conclusion about the below is fine.

> Yes let's see if we can isolate the "final" block and (without repeating code) use in both system prompt and that final block.

2024-10-05 23:42 UTC, pseudotensor approved these changes

2024-10-05 23:42 UTC, merged