Add weaviate support
h2oai/h2ogpt pull request #218
Opened 2023-06-01 09:43 UTC by hsm207

Fixes #145

2023-06-01 16:40 UTC, hsm207 commented
@pseudotensor could you please review this PR?

2023-06-01 20:51 UTC, pseudotensor approved these changes
Awesome thanks!

2023-06-01 21:01 UTC, pseudotensor commented
@achraf-mer we are getting contributors, would be great to have jenkins smoke going!

2023-06-01 21:17 UTC, pseudotensor requested changes
Just a few changes, that the Author of PR also brought up.

2023-06-02 00:35 UTC, hsm207 commented
@pseudotensor 

For point 1:

> Please provide an output of:
> pytest -s -v tests/test_langchain_units.py::test_qa_wiki_db_chunk_hf_weaviate

What do you mean by "provide the output of the test"? Do you mean you want me to paste the output of the test in this PR's description?

For point 2:

> Let's pass a verbose through to the weaviate client or other places. I don't see that currently.

Are you okay with me introducing a new param called `verbose` to the `get_db()` function to control the embedded weaviate's verbosity?

I also plan to add an option to connect to weaviate on a local docker instance too. For this method, the user needs to provide url, username and password (only the url is compulsory). 

I'm leaning towards configuring the connection methods using environment variables instead of adding additional params to the functions. What do you think?

2023-06-02 00:56 UTC, pseudotensor commented
Hi, I just mean please run the test and show it pass etc.

Yes, please add a new verbose parameter.

For make_db, yes let's do minimal required work for now and un-hardcode things.

Yes, for docker etc. can then add the remote client etc.  In a different PR.

2023-06-02 17:39 UTC, hsm207 commented
@pseudotensor I've addressed your feedback.

For point 2, it is not possible to silent the weaviate client. I've raised a feature request for this (see weaviate/weaviate-python-client#346 )

2023-06-02 19:46 UTC, pseudotensor commented
```
============================================================================================================ short test summary info ============================================================================================================
FAILED tests/test_langchain_units.py::test_md_add - AssertionError: assert 'h2oGPT is a large language model' in 'LangChain file types supported\n\nCLI Database control\n\nWhy h2oGPT for Doc Q&A\n\nFAQ\n\nUseful Links\n\nFine-Tuning\n\nDocker\n\nTriton\n\nAcknowledgements\n\nWhy H2O.ai?\...
================================================================================== 1 failed, 25 passed, 7 skipped, 1 xpassed, 8 warnings in 400.35s (0:06:40) ===================================================================================
(h2ollm) jon@pseudotensor:~/h2ogpt$ 

```


I'll fix that test, unrelated to this PR, and add make_db_main() tests in another PR.

2023-06-02 19:46 UTC, pseudotensor approved these changes

2023-06-02 19:57 UTC, merged

2023-06-02 19:58 UTC, pseudotensor commented
@hsm207 Thanks so much for your contribution!!

2023-06-02 20:21 UTC, pseudotensor commented
@hsm207 Some issues with the changes when adding more coverage: https://github.com/h2oai/h2ogpt/pull/231

2023-06-02 20:23 UTC, pseudotensor commented
Even pycharm showed problems, and `db` wasn't returned.  Trying tests again after changes