feat: add heap telemetry
h2oai/h2ogpt pull request #543
Opened 2023-07-26 04:54 UTC by mmalohlava

The change enables Heap telemetry in Gradio UI to be able to improve
user experience.
The default tracking app id point to Heap project `Main` and its `Development` environment.

For any H2O.ai deployment we should use tracking app id from Heap
project `Main` and environment `Production`. @mmalohlava or from
@mtanco.

The analytics DO NOT track any prompts, only user interactions in UI
(click on buttons, links).

2023-07-26 05:01 UTC, mmalohlava commented
@johnygomez @mtanco pls check

2023-07-26 06:36 UTC, pseudotensor reviewed
Needs to be disabled by default and enabled via CLI option only.  Any keys should be removed from repo and passed on CLI.

2023-07-26 06:37 UTC, pseudotensor requested changes
1

2023-07-26 09:00 UTC, johnygomez approved these changes
LGTM, thanks Michal, I have just a few points to double-check.

2023-07-26 09:00 UTC, johnygomez commented on src/gradio_themes.py
> +        () => {{
nit: Why it needs to have double brackets?

2023-07-26 09:00 UTC, johnygomez commented on src/gradio_runner.py
> +        demo.load(None, None, None, _js=app_js)
QQ: Just to double-check, when exactly is this script called on the UI side? Is it when the page is loaded? Note that the heap script is downloading and using additional scripts, which could be a problem if called in some weird way or sandboxed. I assume however it's tested and it's working.

2023-07-31 15:36 UTC, mmalohlava commented on src/gradio_themes.py
> +        () => {{
string interpolation requires it - f-string "{}" is treated as a reference to variable.

2023-07-31 15:37 UTC, mmalohlava commented
@pseudotensor 
> Needs to be disabled by default and enabled via CLI option only. Any keys should be removed from repo and passed on CLI.
the whole point is to collect telemetry to improve our understanding of end-users.

2023-08-03 16:47 UTC, arnocandel approved these changes

2023-08-03 23:43 UTC, pseudotensor approved these changes

2023-08-03 23:43 UTC, merged